spring:
  application:
    name: TuningPrototype
  cloud:
    aws:
      region:
        static: ${AWS_REGION}
#        profile:
#    Not needed since EC2/EKS instances should read from IAM role, uncomment if static properties are needed
#          name: default
#          access-key: ${AWS_ACCESS_KEY_ID}
#          secret-key: ${AWS_SECRET_ACCESS_KEY}
  #
  #   Temporarily disable this because kinesis is not on free tier. Using SQS instead.
  #    stream:
  #      bindings:
  #        # <identifier>-<in/out>-<index>
  #        publishSamplingAgentEvent-out-0:
  #          destination: sampling_agent_event_stream
  config:
    import: "aws-secretsmanager:tuning_server_secrets"
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        default_batch_fetch_size: 20
  ai:
    mcp:
      server:
        protocol: STREAMABLE
        streamable-http:
          keep-alive-interval: 30s

server:
  port: 8080

app:
  datasource:
    url: jdbc:mysql://strategy-tuning-db-instance.cv26muqooyrk.ap-southeast-2.rds.amazonaws.com:3306/strategy_tuning_db?serverTimezone=UTC&ssl=true&sslmode=verify-full&sslrootcert=/certs/global-bundle.pem
    username: ${STRATEGY_TUNING_DB_ADMIN_USER}
    password: ${STRATEGY_TUNING_DB_ADMIN_PASS}
    configuration:
      maximum-pool-size: 30
      driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    root: info
  file:
    name: logs/application.log
